change path

diff --git a/.github/workflows/e2e-functional-template.yml b/.github/workflows/e2e-functional-template.yml
--- a/.github/workflows/e2e-functional-template.yml
+++ b/.github/workflows/e2e-functional-template.yml
@@ -190,8 +190,7 @@ jobs:
             export DISPLAY=:99
             Xvfb $DISPLAY -screen 0 1280x960x24 > /dev/null 2>&1 &
           fi
-          npm run e2e || true # making job pass even if the tests fail due to flakyness
-          cd e2e
+          npm run run:e2e || true # making job pass even if the tests fail due to flakyness
           npm run send-report
         env:
           SERVER_VERSION: ${{ inputs.MM_SERVER_VERSION}}
