test - 11

diff --git a/.github/workflows/e2e-functional.yml b/.github/workflows/e2e-functional.yml
--- a/.github/workflows/e2e-functional.yml
+++ b/.github/workflows/e2e-functional.yml
@@ -29,56 +29,56 @@ env:
 
 
 jobs:
-  e2e-linux:
-    if: ${{ github.event.label.name == 'Run Desktop E2E Tests' }}
-    runs-on: ubuntu-latest
-    steps:
+  # e2e-linux:
+  #   if: ${{ github.event.label.name == 'Run Desktop E2E Tests' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
 
-      - name: ci/checkout-repo
-        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
-      - name: ci/setup-node
-        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
-        with:
-          node-version-file: "package.json"
-          cache: "npm"
-          cache-dependency-path: package-lock.json
+  #     - name: ci/checkout-repo
+  #       uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
+  #     - name: ci/setup-node
+  #       uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
+  #       with:
+  #         node-version-file: "package.json"
+  #         cache: "npm"
+  #         cache-dependency-path: package-lock.json
 
-      - name: Install dependencies
-        env:
-          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
-        run: |
-          wget -qO - https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key | sudo apt-key add -
-          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
-          sudo apt-get update || true && sudo apt-get install -y ca-certificates libxtst-dev libpng++-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu jq icnsutils graphicsmagick tzdata
-          npm ci
+  #     - name: Install dependencies
+  #       env:
+  #         PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
+  #       run: |
+  #         wget -qO - https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_22.04/Release.key | sudo apt-key add -
+  #         wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.20.1/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
+  #         sudo apt-get update || true && sudo apt-get install -y ca-certificates libxtst-dev libpng++-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu jq icnsutils graphicsmagick tzdata
+  #         npm ci
 
-      - name: Set Environment Variables
-        run: |
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
-          echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
-          echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
-          elif [ "${{ github.event_name }}" == "release" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
-            echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
-            echo "ZEPHYR_ENABLE=true" >> $GITHUB_ENV
-          elif [ "${{ github.event_name }}" == "schedule" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
-            echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
-          fi
-          echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
-          echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
-          echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+  #     - name: Set Environment Variables
+  #       run: |
+  #         if [ "${{ github.event_name }}" == "pull_request" ]; then
+  #         echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+  #         echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
+  #         elif [ "${{ github.event_name }}" == "release" ]; then
+  #           echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+  #           echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
+  #           echo "ZEPHYR_ENABLE=true" >> $GITHUB_ENV
+  #         elif [ "${{ github.event_name }}" == "schedule" ]; then
+  #           echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+  #           echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
+  #         fi
+  #         echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
+  #         echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
+  #         echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV
 
-          if [ -n "${ZEPHYR_ENABLE}" ]; then
-            echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
-          fi
+  #         if [ -n "${ZEPHYR_ENABLE}" ]; then
+  #           echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
+  #         fi
 
-      - name: Run Playwright tests (Ubuntu OS)
-        run: |
-          export DISPLAY=:99
-          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
-          npm run test:e2e || true # making job pass even if the tests fail due to flakyness
-          npm run test:e2e:send-report
+  #     - name: Run Playwright tests (Ubuntu OS)
+  #       run: |
+  #         export DISPLAY=:99
+  #         Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
+  #         npm run test:e2e || true # making job pass even if the tests fail due to flakyness
+  #         npm run test:e2e:send-report
     
   e2e-macos:
     if: ${{ github.event.label.name == 'Run Desktop E2E Tests' }}
@@ -104,9 +104,6 @@ jobs:
         run: |
           jq '.mac.target=["zip"]' electron-builder.json | jq '.mac.gatekeeperAssess=false' > /tmp/electron-builder.json && cp /tmp/electron-builder.json .
           npm ci
-          npm i robotjs
-          npm i -D electron-rebuild
-          npm install -g node-gyp
           npx electron-rebuild -f -t prod,optional,dev -w robotjs
 
       - name: Set Environment Variables
@@ -135,73 +132,73 @@ jobs:
           npm run test:e2e || true # making job pass even if the tests fail due to flakyness
           npm run test:e2e:send-report
 
-  e2e-windows:
-    if: ${{ github.event.label.name == 'Run Desktop E2E Tests' }}
-    runs-on: windows-2022
-    steps:
-      - name: ci/checkout-repo
-        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
-      - name: ci/setup-node
-        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
-        with:
-          node-version-file: "package.json"
-          cache: "npm"
-          cache-dependency-path: package-lock.json
+  # e2e-windows:
+  #   if: ${{ github.event.label.name == 'Run Desktop E2E Tests' }}
+  #   runs-on: windows-2022
+  #   steps:
+  #     - name: ci/checkout-repo
+  #       uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
+  #     - name: ci/setup-node
+  #       uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
+  #       with:
+  #         node-version-file: "package.json"
+  #         cache: "npm"
+  #         cache-dependency-path: package-lock.json
 
-      - name: ci/cache-node-modules
-        id: cache-node-modules
-        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
-        with:
-          path: node_modules
-          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-build-node-modules
-            ${{ runner.os }}-build-
-            ${{ runner.os }}-
+  #     - name: ci/cache-node-modules
+  #       id: cache-node-modules
+  #       uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
+  #       with:
+  #         path: node_modules
+  #         key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-build-node-modules
+  #           ${{ runner.os }}-build-
+  #           ${{ runner.os }}-
 
-      - name: ci/install-node-gyp
-        if: steps.cache-node-modules.outputs.cache-hit != 'true'
-        env:
-          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-        run: |
-          choco install yq --version 4.15.1 -y
-          npm i -g node-gyp
-          node-gyp install
-          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers"
-          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch arm64
-          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch ia32
-          npm ci --openssl_fips=''
+  #     - name: ci/install-node-gyp
+  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
+  #       env:
+  #         PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+  #       run: |
+  #         choco install yq --version 4.15.1 -y
+  #         npm i -g node-gyp
+  #         node-gyp install
+  #         node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers"
+  #         node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch arm64
+  #         node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers" --arch ia32
+  #         npm ci --openssl_fips=''
 
-      - name: Set Environment Variables
-        shell: bash
-        run: |
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
-            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
-            echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
-          elif [ "${{ github.event_name }}" == "release" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
-            echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
-            echo "ZEPHYR_ENABLE=true" >> $GITHUB_ENV
-          elif [ "${{ github.event_name }}" == "schedule" ]; then
-            echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
-            echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
-          fi
-          echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
-          echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
-          echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+  #     - name: Set Environment Variables
+  #       shell: bash
+  #       run: |
+  #         if [ "${{ github.event_name }}" == "pull_request" ]; then
+  #           echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+  #           echo "BUILD_SUFFIX=desktop-pr" >> $GITHUB_ENV
+  #         elif [ "${{ github.event_name }}" == "release" ]; then
+  #           echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+  #           echo "BUILD_SUFFIX=desktop-release" >> $GITHUB_ENV
+  #           echo "ZEPHYR_ENABLE=true" >> $GITHUB_ENV
+  #         elif [ "${{ github.event_name }}" == "schedule" ]; then
+  #           echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
+  #           echo "BUILD_SUFFIX=desktop-nightly" >> $GITHUB_ENV
+  #         fi
+  #         echo "BUILD_ID=${{ github.run_id }}-${BUILD_SUFFIX}-${{ runner.os }}" >> $GITHUB_ENV
+  #         echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
+  #         echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV
 
-          if [ -n "${ZEPHYR_ENABLE}" ]; then
-            echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
-          fi
+  #         if [ -n "${ZEPHYR_ENABLE}" ]; then
+  #           echo "ZEPHYR_ENABLE=${ZEPHYR_ENABLE}" >> $GITHUB_ENV
+  #         fi
   
-      - name: Run Playwright tests (Windows OS)
-        run: |
-          npm run test:e2e || true
-          npm run test:e2e:send-report
-        shell: bash
+  #     - name: Run Playwright tests (Windows OS)
+  #       run: |
+  #         npm run test:e2e || true
+  #         npm run test:e2e:send-report
+  #       shell: bash
 
   e2e-remove-label:
-    needs: [e2e-linux, e2e-macos, e2e-windows]
+    needs: [e2e-macos]
     if: ${{ github.event.label.name == 'Run Desktop E2E Tests' }} && always()
     runs-on: ubuntu-latest
     steps:
