clean up

diff --git a/.github/workflows/e2e-functional.yml b/.github/workflows/e2e-functional.yml
--- a/.github/workflows/e2e-functional.yml
+++ b/.github/workflows/e2e-functional.yml
@@ -152,10 +152,15 @@ jobs:
 
       - name: Run mattermsot server & Playwright tests (macOS)
         run: |
+          LATEST_RELEASE_TAG=$(curl -L -s https://api.github.com/repos/mattermost/mattermost-server/releases/latest | jq -r '.tag_name')
+          LATEST_RELEASE_TAG="${LATEST_RELEASE_TAG#v}"
           cd mattermost/e2e-tests
-          echo "SERVER_IMAGE=mattermost/mattermost-enterprise-edition:release-8.0" >.ci/env
+          echo "SERVER_IMAGE=mattermost/mattermost-enterprise-edition:$LATEST_RELEASE_TAG" >.ci/env
           make start-server && make prepare-server
-          npm run test:e2e || true
+
+      - name: Run Playwright tests (macOS)
+        run: |
+          npm run test:e2e || true # making job pass even if the tests fail due to flakyness
           npm run test:e2e:send-report
 
   e2e-windows:
