run tests

diff --git a/.github/workflows/e2e-functional-template.yml b/.github/workflows/e2e-functional-template.yml
--- a/.github/workflows/e2e-functional-template.yml
+++ b/.github/workflows/e2e-functional-template.yml
@@ -153,10 +153,6 @@ jobs:
           cd e2e
           npm ci
           npx electron-rebuild --platform=linux -f -t prod,optional,dev -w robotjs --module-dir ../
-          echo "************"
-          pwd
-          ls -a
-          echo "************"
 
       - name: e2e/install-dependencies-macos
         if: runner.os == 'macOS'
@@ -168,10 +164,6 @@ jobs:
           cd e2e
           npm ci
           npx electron-rebuild --platform=darwin -f -t prod,optional,dev -w robotjs --module-dir ../
-          echo "************"
-          pwd
-          ls -a
-          echo "************"
 
       ## Windows Dependencies
       - name: e2e/install-dependencies-windows
@@ -188,10 +180,6 @@ jobs:
           cd e2e
           npm ci
           npx electron-rebuild --platform=win32 -f -t prod,optional,dev -w robotjs --module-dir ../
-          echo "************"
-          pwd
-          ls -a
-          echo "************"
 
       - name: e2e/run-playright-tests-${{ runner.os }}
         run: |
@@ -199,12 +187,9 @@ jobs:
             export DISPLAY=:99
             Xvfb $DISPLAY -screen 0 1280x960x24 > /dev/null 2>&1 &
           fi
-          echo "************"
-          pwd
-          ls -a
-          echo "************"
-          npm run e2e || true # making job pass even if the tests fail due to flakyness
+          npm run build-test
           cd e2e
+          npm run run || true # making job pass even if the tests fail due to flakyness
           npm run send-report
         env:
           SERVER_VERSION: ${{ inputs.MM_SERVER_VERSION}}
