updated jobs with proper secrets

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -30,7 +30,7 @@ jobs:
             \"icon_url\": \"https://mattermost.com/wp-content/uploads/2022/02/icon.png\",
             \"text\": \"[${VERSION}] Release process for the desktop app has started, it should take about 30 minutes to complete.\"
           }" >> /tmp/webhook-data.json
-          curl -i -H "Content-Type: application/json" -X POST -d @/tmp/webhook-data.json ${{ secrets.MATTERMOST_RELEASE_WEBHOOK_URL_DESKTOP }} || echo "NOFICATION FAILED! check logs as this will succeed intentionally"
+          curl -i -H "Content-Type: application/json" -X POST -d @/tmp/webhook-data.json ${{ secrets.MM_DESKTOP_RELEASE_WEBHOOK_URL }} || echo "NOFICATION FAILED! check logs as this will succeed intentionally"
 
   build-linux:
     runs-on: ubuntu-22.04
@@ -97,6 +97,12 @@ jobs:
         uses: ./.github/actions/test
       - name: release/build
         shell: powershell
+        env:
+          MM_WIN_INSTALLERS: 1
+          PFX_KEY: ${{ secrets.MM_DESKTOP_MSI_INSTALLER_PFX_KEY }}
+          CSC_KEY_PASSWORD: ${{ secrets.MM_DESKTOP_MSI_INSTALLER_CSC_KEY_PASSWORD }}
+          PFX: ${{ secrets.MM_DESKTOP_MSI_INSTALLER_PFX }}
+          CSC_LINK: ${{ secrets.MM_DESKTOP_MSI_INSTALLER_CSC_LINK }}
         run: |
           ./scripts/Makefile.ps1 build
       - name: release/package
@@ -133,6 +139,12 @@ jobs:
       - name: release/test
         uses: ./.github/actions/test
       - name: release/build
+        env:
+          APPLEID: ${{ secrets.MM_DESKTOP_MAC_INSTALLER_APPLE_ID }}
+          APPLEIDPASS: ${{ secrets.MM_DESKTOP_MAC_INSTALLER_APPLE_ID_PASS }}
+          CSC_FOR_PULL_REQUEST: true
+          CSC_KEY_PASSWORD: ${{ secrets.MM_DESKTOP_MAC_INSTALLER_CSC_KEY_PASSWORD }}
+          CSC_LINK: ${{ secrets.MM_DESKTOP_MAC_INSTALLER_CSC_LINK }}
         run: |
           npm run package:mac-with-universal
           bash -x ./scripts/patch_updater_yml.sh
@@ -149,6 +161,14 @@ jobs:
 
   mac-app-store-preflight:
     runs-on: macos-12
+    env:
+      MAS_PROFILE: ${{ secrets.MM_DESKTOP_MAC_APP_STORE_MAS_PROFILE }}
+      MACOS_API_KEY_ID: ${{ secrets.MM_DESKTOP_MAC_APP_STORE_MACOS_API_KEY_ID }}
+      MACOS_API_KEY: ${{ secrets.MM_DESKTOP_MAC_APP_STORE_MACOS_API_KEY }}
+      MACOS_API_ISSUER_ID: ${{ secrets.MM_DESKTOP_MAC_APP_STORE_MACOS_API_ISSUER_ID }}
+      CSC_FOR_PULL_REQUEST: true
+      CSC_KEY_PASSWORD: ${{ secrets.MM_DESKTOP_MAC_APP_STORE_CSC_KEY_PASSWORD}}
+      CSC_LINK: ${{ secrets.MM_DESKTOP_MAC_APP_STORE_CSC_LINK }}
     needs:
       - begin-notification
     steps:
@@ -184,6 +204,12 @@ jobs:
       - build-msi-installer
       - build-linux
     steps:
+      - name: release/setup-aws-credentials
+        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
+        with:
+          aws-region: us-east-1
+          aws-access-key-id: ${{ secrets.MM_DESKTOP_RELEASE_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.MM_DESKTOP_RELEASE_AWS_SECRET_KEY }}
       - name: release/download-builds
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
       - name: release/setup-files-for-aws
@@ -233,4 +259,4 @@ jobs:
             \"icon_url\": \"https://mattermost.com/wp-content/uploads/2022/02/icon.png\",
             \"text\": \"[${VERSION}] Release process for the desktop app ended, the new release can be found on [GitHub](https://github.com/mattermost/desktop/releases).\"
           }" >> /tmp/webhook-data.json
-          curl -i -H "Content-Type: application/json" -X POST -d @/tmp/webhook-data.json ${{ secrets.MATTERMOST_RELEASE_WEBHOOK_URL_DESKTOP }} || echo "NOFICATION FAILED! check logs as this will succeed intentionally"
+          curl -i -H "Content-Type: application/json" -X POST -d @/tmp/webhook-data.json ${{ secrets.MM_DESKTOP_RELEASE_WEBHOOK_URL }} || echo "NOFICATION FAILED! check logs as this will succeed intentionally"
